<center>
   <span style="color:red; font-size:30px">
      ORACLE
   </span>
</center>

<span style="color:blue; font-size:15px">
   BIBLIOTECA: 
   <span style="color:purple; font-size:15px">
    ORACLE-PYTHON
   </span>
</span>

In [ ]:
!pip install oracledb

<span style="color:blue; font-size:15px">
   EJEMPLO 01: 
   <span style="color:purple; font-size:15px">
      CONEXION ORACLE-PYTHON
   </span>
</span>

In [ ]:
import oracledb

def ejemplo1():
    conexion = None
    try:
        conexion = oracledb.connect(
            user = "bd16052025",
            password = "12345678",
            dsn = "localhost:1521/xepdb1"
        )
    except Exception as e:
        print("Error: Conexion ", e)
    
    if conexion != None:
       print("Ok: Conexion")
    else:
       print("Error: Conexion") 

def main():
    ejemplo1()

if __name__ == "__main__":
    main()

<span style="color:blue; font-size:15px">
   EJEMPLO 02: 
   <span style="color:purple; font-size:15px">
      SELECT
   </span>
</span>

In [ ]:
!pip install tabulate

In [3]:
import oracledb
from tabulate import tabulate

def ejemplo1():
    conexion = None
    try:
        conexion = oracledb.connect(
            user = "bd16052025",
            password = "12345678",
            dsn = "localhost:1521/xepdb1"
        )
    except Exception as e:
        print("Error: Conexion ", e)
    
    if conexion != None:
       print("Ok: Conexion")
    
       query = "SELECT * FROM Persona"
       cursor = conexion.cursor()
       cursor.execute(query)
       lista_tuplas = cursor.fetchall()
       print(lista_tuplas)
        
       for tupla in lista_tuplas:
           print(tupla)
            
       encabezados = ["IDPERSONA","NOMBRE","EDAD","ALTURA","CASADO","FECHA_NAC"]
    
       print(tabulate(lista_tuplas, headers=encabezados, tablefmt="fancy_grid"))
    
    
    else:
       print("Error: Conexion") 

def main():
    ejemplo1()

if __name__ == "__main__":
    main()

Ok: Conexion
[(1, 'Juan Pérez', 30, 1.75, 'S', datetime.datetime(1994, 5, 16, 0, 0)), (2, 'María Gómez', 28, 1.65, 'N', datetime.datetime(1996, 3, 10, 0, 0)), (3, 'Carlos Ruiz', 35, 1.8, 'S', datetime.datetime(1989, 7, 21, 0, 0)), (4, 'Lucía Fernández', 22, 1.6, 'N', datetime.datetime(2002, 1, 30, 0, 0)), (5, 'Pedro Sánchez', 40, 1.78, 'S', datetime.datetime(1984, 12, 5, 0, 0)), (6, 'Ana Torres', 27, 1.68, 'N', datetime.datetime(1997, 8, 15, 0, 0)), (7, 'Luis Martínez', 31, 1.72, 'S', datetime.datetime(1993, 11, 9, 0, 0)), (8, 'Isabel Díaz', 45, 1.63, 'S', datetime.datetime(1979, 6, 1, 0, 0)), (9, 'Diego Romero', 19, 1.82, 'N', datetime.datetime(2005, 9, 14, 0, 0)), (10, 'Claudia Navarro', 33, 1.7, 'S', datetime.datetime(1991, 2, 18, 0, 0)), (11, 'José Herrera', 29, 1.76, 'N', datetime.datetime(1995, 4, 22, 0, 0)), (12, 'Valeria Castro', 24, 1.61, 'N', datetime.datetime(2000, 7, 30, 0, 0)), (13, 'Andrés Molina', 36, 1.85, 'S', datetime.datetime(1988, 3, 3, 0, 0)), (14, 'Patricia León', 38, 1.66, 'S', datetime.datetime(1986, 12, 28, 0, 0)), (15, 'Hugo Paredes', 26, 1.79, 'N', datetime.datetime(1998, 5, 11, 0, 0)), (16, 'Sofía Ortega', 23, 1.58, 'N', datetime.datetime(2001, 10, 5, 0, 0)), (17, 'Manuel Cordero', 41, 1.74, 'S', datetime.datetime(1983, 9, 17, 0, 0)), (18, 'Gabriela Fuentes', 32, 1.67, 'S', datetime.datetime(1992, 6, 9, 0, 0)), (19, 'Ricardo Peña', 21, 1.81, 'N', datetime.datetime(2003, 8, 22, 0, 0)), (20, 'Marta Salas', 34, 1.62, 'S', datetime.datetime(1990, 4, 12, 0, 0)), (21, 'Fernando Ríos', 39, 1.77, 'S', datetime.datetime(1985, 2, 2, 0, 0)), (22, 'Camila Durán', 25, 1.64, 'N', datetime.datetime(1999, 1, 19, 0, 0)), (23, 'Tomás Aguilar', 37, 1.83, 'S', datetime.datetime(1987, 10, 13, 0, 0)), (24, 'Elena Ramos', 20, 1.59, 'N', datetime.datetime(2004, 12, 7, 0, 0)), (25, 'Iván Varela', 27, 1.71, 'N', datetime.datetime(1997, 11, 26, 0, 0)), (26, 'Natalia Jiménez', 31, 1.69, 'S', datetime.datetime(1993, 6, 23, 0, 0)), (27, 'Fabián Cabrera', 29, 1.84, 'N', datetime.datetime(1995, 5, 9, 0, 0)), (28, 'Laura Méndez', 26, 1.63, 'N', datetime.datetime(1998, 9, 30, 0, 0)), (29, 'Samuel Bravo', 42, 1.78, 'S', datetime.datetime(1982, 11, 20, 0, 0)), (30, 'Daniela Vega', 35, 1.6, 'S', datetime.datetime(1989, 2, 27, 0, 0)), (31, 'Esteban Sáenz', 33, 1.82, 'S', datetime.datetime(1991, 1, 11, 0, 0)), (32, 'Julieta Mora', 22, 1.57, 'N', datetime.datetime(2002, 6, 6, 0, 0)), (33, 'Benjamín Torres', 28, 1.76, 'N', datetime.datetime(1996, 7, 3, 0, 0)), (34, 'Ángela Suárez', 36, 1.68, 'S', datetime.datetime(1988, 8, 18, 0, 0)), (35, 'Adrián Lozano', 24, 1.7, 'N', datetime.datetime(2000, 5, 1, 0, 0)), (36, 'Noelia Medina', 30, 1.62, 'S', datetime.datetime(1994, 3, 25, 0, 0)), (37, 'Cristian Lara', 38, 1.79, 'S', datetime.datetime(1986, 4, 14, 0, 0)), (38, 'Silvia Barrios', 27, 1.61, 'N', datetime.datetime(1997, 10, 28, 0, 0)), (39, 'Matías Rojas', 23, 1.73, 'N', datetime.datetime(2001, 12, 12, 0, 0)), (40, 'Rocío Acosta', 32, 1.65, 'S', datetime.datetime(1992, 7, 8, 0, 0)), (41, 'Agustín Castillo', 40, 1.8, 'S', datetime.datetime(1984, 9, 4, 0, 0)), (42, 'Victoria Serrano', 34, 1.67, 'S', datetime.datetime(1990, 8, 2, 0, 0)), (43, 'Javier Salgado', 25, 1.75, 'N', datetime.datetime(1999, 11, 6, 0, 0)), (44, 'Paula Quintero', 28, 1.6, 'N', datetime.datetime(1996, 2, 24, 0, 0)), (45, 'Emilio Estrada', 39, 1.77, 'S', datetime.datetime(1985, 5, 19, 0, 0)), (46, 'Melina Guerra', 21, 1.59, 'N', datetime.datetime(2003, 3, 16, 0, 0)), (47, 'Leandro Vargas', 37, 1.83, 'S', datetime.datetime(1987, 6, 30, 0, 0)), (48, 'Antonia Herrera', 20, 1.62, 'N', datetime.datetime(2004, 1, 2, 0, 0)), (49, 'Sebastián Carrillo', 26, 1.74, 'N', datetime.datetime(1998, 8, 19, 0, 0)), (50, 'Carmen Reyes', 33, 1.68, 'S', datetime.datetime(1991, 9, 25, 0, 0))]
(1, 'Juan Pérez', 30, 1.75, 'S', datetime.datetime(1994, 5, 16, 0, 0))
(2, 'María Gómez', 28, 1.65, 'N', datetime.datetime(1996, 3, 10, 0, 0))
(3, 'Carlos Ruiz', 35, 1.8, 'S', datetime.datetime(1989, 7, 21, 0, 0))
(4, 'Lucía Fernández', 22, 1.6, 'N', datetime.datetime(2002, 1, 30, 0, 0))
(5, 'Pedro Sánchez', 40, 1.78, 'S', datetime.datetime(1984, 12, 5, 0, 0))
(6, 'Ana Torres', 27, 1.68, 'N', datetime.datetime(1997, 8, 15, 0, 0))
(7, 'Luis Martínez', 31, 1.72, 'S', datetime.datetime(1993, 11, 9, 0, 0))
(8, 'Isabel Díaz', 45, 1.63, 'S', datetime.datetime(1979, 6, 1, 0, 0))
(9, 'Diego Romero', 19, 1.82, 'N', datetime.datetime(2005, 9, 14, 0, 0))
(10, 'Claudia Navarro', 33, 1.7, 'S', datetime.datetime(1991, 2, 18, 0, 0))
(11, 'José Herrera', 29, 1.76, 'N', datetime.datetime(1995, 4, 22, 0, 0))
(12, 'Valeria Castro', 24, 1.61, 'N', datetime.datetime(2000, 7, 30, 0, 0))
(13, 'Andrés Molina', 36, 1.85, 'S', datetime.datetime(1988, 3, 3, 0, 0))
(14, 'Patricia León', 38, 1.66, 'S', datetime.datetime(1986, 12, 28, 0, 0))
(15, 'Hugo Paredes', 26, 1.79, 'N', datetime.datetime(1998, 5, 11, 0, 0))
(16, 'Sofía Ortega', 23, 1.58, 'N', datetime.datetime(2001, 10, 5, 0, 0))
(17, 'Manuel Cordero', 41, 1.74, 'S', datetime.datetime(1983, 9, 17, 0, 0))
(18, 'Gabriela Fuentes', 32, 1.67, 'S', datetime.datetime(1992, 6, 9, 0, 0))
(19, 'Ricardo Peña', 21, 1.81, 'N', datetime.datetime(2003, 8, 22, 0, 0))
(20, 'Marta Salas', 34, 1.62, 'S', datetime.datetime(1990, 4, 12, 0, 0))
(21, 'Fernando Ríos', 39, 1.77, 'S', datetime.datetime(1985, 2, 2, 0, 0))
(22, 'Camila Durán', 25, 1.64, 'N', datetime.datetime(1999, 1, 19, 0, 0))
(23, 'Tomás Aguilar', 37, 1.83, 'S', datetime.datetime(1987, 10, 13, 0, 0))
(24, 'Elena Ramos', 20, 1.59, 'N', datetime.datetime(2004, 12, 7, 0, 0))
(25, 'Iván Varela', 27, 1.71, 'N', datetime.datetime(1997, 11, 26, 0, 0))
(26, 'Natalia Jiménez', 31, 1.69, 'S', datetime.datetime(1993, 6, 23, 0, 0))
(27, 'Fabián Cabrera', 29, 1.84, 'N', datetime.datetime(1995, 5, 9, 0, 0))
(28, 'Laura Méndez', 26, 1.63, 'N', datetime.datetime(1998, 9, 30, 0, 0))
(29, 'Samuel Bravo', 42, 1.78, 'S', datetime.datetime(1982, 11, 20, 0, 0))
(30, 'Daniela Vega', 35, 1.6, 'S', datetime.datetime(1989, 2, 27, 0, 0))
(31, 'Esteban Sáenz', 33, 1.82, 'S', datetime.datetime(1991, 1, 11, 0, 0))
(32, 'Julieta Mora', 22, 1.57, 'N', datetime.datetime(2002, 6, 6, 0, 0))
(33, 'Benjamín Torres', 28, 1.76, 'N', datetime.datetime(1996, 7, 3, 0, 0))
(34, 'Ángela Suárez', 36, 1.68, 'S', datetime.datetime(1988, 8, 18, 0, 0))
(35, 'Adrián Lozano', 24, 1.7, 'N', datetime.datetime(2000, 5, 1, 0, 0))
(36, 'Noelia Medina', 30, 1.62, 'S', datetime.datetime(1994, 3, 25, 0, 0))
(37, 'Cristian Lara', 38, 1.79, 'S', datetime.datetime(1986, 4, 14, 0, 0))
(38, 'Silvia Barrios', 27, 1.61, 'N', datetime.datetime(1997, 10, 28, 0, 0))
(39, 'Matías Rojas', 23, 1.73, 'N', datetime.datetime(2001, 12, 12, 0, 0))
(40, 'Rocío Acosta', 32, 1.65, 'S', datetime.datetime(1992, 7, 8, 0, 0))
(41, 'Agustín Castillo', 40, 1.8, 'S', datetime.datetime(1984, 9, 4, 0, 0))
(42, 'Victoria Serrano', 34, 1.67, 'S', datetime.datetime(1990, 8, 2, 0, 0))
(43, 'Javier Salgado', 25, 1.75, 'N', datetime.datetime(1999, 11, 6, 0, 0))
(44, 'Paula Quintero', 28, 1.6, 'N', datetime.datetime(1996, 2, 24, 0, 0))
(45, 'Emilio Estrada', 39, 1.77, 'S', datetime.datetime(1985, 5, 19, 0, 0))
(46, 'Melina Guerra', 21, 1.59, 'N', datetime.datetime(2003, 3, 16, 0, 0))
(47, 'Leandro Vargas', 37, 1.83, 'S', datetime.datetime(1987, 6, 30, 0, 0))
(48, 'Antonia Herrera', 20, 1.62, 'N', datetime.datetime(2004, 1, 2, 0, 0))
(49, 'Sebastián Carrillo', 26, 1.74, 'N', datetime.datetime(1998, 8, 19, 0, 0))
(50, 'Carmen Reyes', 33, 1.68, 'S', datetime.datetime(1991, 9, 25, 0, 0))
╒═════════════╤════════════════════╤════════╤══════════╤══════════╤═════════════════════╕
│   IDPERSONA │ NOMBRE             │   EDAD │   ALTURA │ CASADO   │ FECHA_NAC           │
╞═════════════╪════════════════════╪════════╪══════════╪══════════╪═════════════════════╡
│           1 │ Juan Pérez         │     30 │     1.75 │ S        │ 1994-05-16 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           2 │ María Gómez        │     28 │     1.65 │ N        │ 1996-03-10 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           3 │ Carlos Ruiz        │     35 │     1.8  │ S        │ 1989-07-21 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           4 │ Lucía Fernández    │     22 │     1.6  │ N        │ 2002-01-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           5 │ Pedro Sánchez      │     40 │     1.78 │ S        │ 1984-12-05 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           6 │ Ana Torres         │     27 │     1.68 │ N        │ 1997-08-15 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           7 │ Luis Martínez      │     31 │     1.72 │ S        │ 1993-11-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           8 │ Isabel Díaz        │     45 │     1.63 │ S        │ 1979-06-01 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           9 │ Diego Romero       │     19 │     1.82 │ N        │ 2005-09-14 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          10 │ Claudia Navarro    │     33 │     1.7  │ S        │ 1991-02-18 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          11 │ José Herrera       │     29 │     1.76 │ N        │ 1995-04-22 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          12 │ Valeria Castro     │     24 │     1.61 │ N        │ 2000-07-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          13 │ Andrés Molina      │     36 │     1.85 │ S        │ 1988-03-03 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          14 │ Patricia León      │     38 │     1.66 │ S        │ 1986-12-28 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          15 │ Hugo Paredes       │     26 │     1.79 │ N        │ 1998-05-11 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          16 │ Sofía Ortega       │     23 │     1.58 │ N        │ 2001-10-05 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          17 │ Manuel Cordero     │     41 │     1.74 │ S        │ 1983-09-17 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          18 │ Gabriela Fuentes   │     32 │     1.67 │ S        │ 1992-06-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          19 │ Ricardo Peña       │     21 │     1.81 │ N        │ 2003-08-22 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          20 │ Marta Salas        │     34 │     1.62 │ S        │ 1990-04-12 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          21 │ Fernando Ríos      │     39 │     1.77 │ S        │ 1985-02-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          22 │ Camila Durán       │     25 │     1.64 │ N        │ 1999-01-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          23 │ Tomás Aguilar      │     37 │     1.83 │ S        │ 1987-10-13 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          24 │ Elena Ramos        │     20 │     1.59 │ N        │ 2004-12-07 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          25 │ Iván Varela        │     27 │     1.71 │ N        │ 1997-11-26 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          26 │ Natalia Jiménez    │     31 │     1.69 │ S        │ 1993-06-23 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          27 │ Fabián Cabrera     │     29 │     1.84 │ N        │ 1995-05-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          28 │ Laura Méndez       │     26 │     1.63 │ N        │ 1998-09-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          29 │ Samuel Bravo       │     42 │     1.78 │ S        │ 1982-11-20 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          30 │ Daniela Vega       │     35 │     1.6  │ S        │ 1989-02-27 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          31 │ Esteban Sáenz      │     33 │     1.82 │ S        │ 1991-01-11 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          32 │ Julieta Mora       │     22 │     1.57 │ N        │ 2002-06-06 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          33 │ Benjamín Torres    │     28 │     1.76 │ N        │ 1996-07-03 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          34 │ Ángela Suárez      │     36 │     1.68 │ S        │ 1988-08-18 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          35 │ Adrián Lozano      │     24 │     1.7  │ N        │ 2000-05-01 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          36 │ Noelia Medina      │     30 │     1.62 │ S        │ 1994-03-25 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          37 │ Cristian Lara      │     38 │     1.79 │ S        │ 1986-04-14 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          38 │ Silvia Barrios     │     27 │     1.61 │ N        │ 1997-10-28 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          39 │ Matías Rojas       │     23 │     1.73 │ N        │ 2001-12-12 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          40 │ Rocío Acosta       │     32 │     1.65 │ S        │ 1992-07-08 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          41 │ Agustín Castillo   │     40 │     1.8  │ S        │ 1984-09-04 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          42 │ Victoria Serrano   │     34 │     1.67 │ S        │ 1990-08-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          43 │ Javier Salgado     │     25 │     1.75 │ N        │ 1999-11-06 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          44 │ Paula Quintero     │     28 │     1.6  │ N        │ 1996-02-24 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          45 │ Emilio Estrada     │     39 │     1.77 │ S        │ 1985-05-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          46 │ Melina Guerra      │     21 │     1.59 │ N        │ 2003-03-16 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          47 │ Leandro Vargas     │     37 │     1.83 │ S        │ 1987-06-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          48 │ Antonia Herrera    │     20 │     1.62 │ N        │ 2004-01-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          49 │ Sebastián Carrillo │     26 │     1.74 │ N        │ 1998-08-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          50 │ Carmen Reyes       │     33 │     1.68 │ S        │ 1991-09-25 00:00:00 │
╘═════════════╧════════════════════╧════════╧══════════╧══════════╧═════════════════════╛

In [5]:
ejemplo1()

Ok: Conexion
[(1, 'Juan Pérez', 30, 1.75, 'S', datetime.datetime(1994, 5, 16, 0, 0)), (2, 'María Gómez', 28, 1.65, 'N', datetime.datetime(1996, 3, 10, 0, 0)), (3, 'Carlos Ruiz', 35, 1.8, 'S', datetime.datetime(1989, 7, 21, 0, 0)), (4, 'Lucía Fernández', 22, 1.6, 'N', datetime.datetime(2002, 1, 30, 0, 0)), (5, 'Pedro Sánchez', 40, 1.78, 'S', datetime.datetime(1984, 12, 5, 0, 0)), (6, 'Ana Torres', 27, 1.68, 'N', datetime.datetime(1997, 8, 15, 0, 0)), (7, 'Luis Martínez', 31, 1.72, 'S', datetime.datetime(1993, 11, 9, 0, 0)), (8, 'Isabel Díaz', 45, 1.63, 'S', datetime.datetime(1979, 6, 1, 0, 0)), (9, 'Diego Romero', 19, 1.82, 'N', datetime.datetime(2005, 9, 14, 0, 0)), (10, 'Claudia Navarro', 33, 1.7, 'S', datetime.datetime(1991, 2, 18, 0, 0)), (11, 'José Herrera', 29, 1.76, 'N', datetime.datetime(1995, 4, 22, 0, 0)), (12, 'Valeria Castro', 24, 1.61, 'N', datetime.datetime(2000, 7, 30, 0, 0)), (13, 'Andrés Molina', 36, 1.85, 'S', datetime.datetime(1988, 3, 3, 0, 0)), (14, 'Patricia León', 38, 1.66, 'S', datetime.datetime(1986, 12, 28, 0, 0)), (15, 'Hugo Paredes', 26, 1.79, 'N', datetime.datetime(1998, 5, 11, 0, 0)), (16, 'Sofía Ortega', 23, 1.58, 'N', datetime.datetime(2001, 10, 5, 0, 0)), (17, 'Manuel Cordero', 41, 1.74, 'S', datetime.datetime(1983, 9, 17, 0, 0)), (18, 'Gabriela Fuentes', 32, 1.67, 'S', datetime.datetime(1992, 6, 9, 0, 0)), (19, 'Ricardo Peña', 21, 1.81, 'N', datetime.datetime(2003, 8, 22, 0, 0)), (20, 'Marta Salas', 34, 1.62, 'S', datetime.datetime(1990, 4, 12, 0, 0)), (21, 'Fernando Ríos', 39, 1.77, 'S', datetime.datetime(1985, 2, 2, 0, 0)), (22, 'Camila Durán', 25, 1.64, 'N', datetime.datetime(1999, 1, 19, 0, 0)), (23, 'Tomás Aguilar', 37, 1.83, 'S', datetime.datetime(1987, 10, 13, 0, 0)), (24, 'Elena Ramos', 20, 1.59, 'N', datetime.datetime(2004, 12, 7, 0, 0)), (25, 'Iván Varela', 27, 1.71, 'N', datetime.datetime(1997, 11, 26, 0, 0)), (26, 'Natalia Jiménez', 31, 1.69, 'S', datetime.datetime(1993, 6, 23, 0, 0)), (27, 'Fabián Cabrera', 29, 1.84, 'N', datetime.datetime(1995, 5, 9, 0, 0)), (28, 'Laura Méndez', 26, 1.63, 'N', datetime.datetime(1998, 9, 30, 0, 0)), (29, 'Samuel Bravo', 42, 1.78, 'S', datetime.datetime(1982, 11, 20, 0, 0)), (30, 'Daniela Vega', 35, 1.6, 'S', datetime.datetime(1989, 2, 27, 0, 0)), (31, 'Esteban Sáenz', 33, 1.82, 'S', datetime.datetime(1991, 1, 11, 0, 0)), (32, 'Julieta Mora', 22, 1.57, 'N', datetime.datetime(2002, 6, 6, 0, 0)), (33, 'Benjamín Torres', 28, 1.76, 'N', datetime.datetime(1996, 7, 3, 0, 0)), (34, 'Ángela Suárez', 36, 1.68, 'S', datetime.datetime(1988, 8, 18, 0, 0)), (35, 'Adrián Lozano', 24, 1.7, 'N', datetime.datetime(2000, 5, 1, 0, 0)), (36, 'Noelia Medina', 30, 1.62, 'S', datetime.datetime(1994, 3, 25, 0, 0)), (37, 'Cristian Lara', 38, 1.79, 'S', datetime.datetime(1986, 4, 14, 0, 0)), (38, 'Silvia Barrios', 27, 1.61, 'N', datetime.datetime(1997, 10, 28, 0, 0)), (39, 'Matías Rojas', 23, 1.73, 'N', datetime.datetime(2001, 12, 12, 0, 0)), (40, 'Rocío Acosta', 32, 1.65, 'S', datetime.datetime(1992, 7, 8, 0, 0)), (41, 'Agustín Castillo', 40, 1.8, 'S', datetime.datetime(1984, 9, 4, 0, 0)), (42, 'Victoria Serrano', 34, 1.67, 'S', datetime.datetime(1990, 8, 2, 0, 0)), (43, 'Javier Salgado', 25, 1.75, 'N', datetime.datetime(1999, 11, 6, 0, 0)), (44, 'Paula Quintero', 28, 1.6, 'N', datetime.datetime(1996, 2, 24, 0, 0)), (45, 'Emilio Estrada', 39, 1.77, 'S', datetime.datetime(1985, 5, 19, 0, 0)), (46, 'Melina Guerra', 21, 1.59, 'N', datetime.datetime(2003, 3, 16, 0, 0)), (47, 'Leandro Vargas', 37, 1.83, 'S', datetime.datetime(1987, 6, 30, 0, 0)), (48, 'Antonia Herrera', 20, 1.62, 'N', datetime.datetime(2004, 1, 2, 0, 0)), (49, 'Sebastián Carrillo', 26, 1.74, 'N', datetime.datetime(1998, 8, 19, 0, 0)), (50, 'Carmen Reyes', 33, 1.68, 'S', datetime.datetime(1991, 9, 25, 0, 0))]
(1, 'Juan Pérez', 30, 1.75, 'S', datetime.datetime(1994, 5, 16, 0, 0))
(2, 'María Gómez', 28, 1.65, 'N', datetime.datetime(1996, 3, 10, 0, 0))
(3, 'Carlos Ruiz', 35, 1.8, 'S', datetime.datetime(1989, 7, 21, 0, 0))
(4, 'Lucía Fernández', 22, 1.6, 'N', datetime.datetime(2002, 1, 30, 0, 0))
(5, 'Pedro Sánchez', 40, 1.78, 'S', datetime.datetime(1984, 12, 5, 0, 0))
(6, 'Ana Torres', 27, 1.68, 'N', datetime.datetime(1997, 8, 15, 0, 0))
(7, 'Luis Martínez', 31, 1.72, 'S', datetime.datetime(1993, 11, 9, 0, 0))
(8, 'Isabel Díaz', 45, 1.63, 'S', datetime.datetime(1979, 6, 1, 0, 0))
(9, 'Diego Romero', 19, 1.82, 'N', datetime.datetime(2005, 9, 14, 0, 0))
(10, 'Claudia Navarro', 33, 1.7, 'S', datetime.datetime(1991, 2, 18, 0, 0))
(11, 'José Herrera', 29, 1.76, 'N', datetime.datetime(1995, 4, 22, 0, 0))
(12, 'Valeria Castro', 24, 1.61, 'N', datetime.datetime(2000, 7, 30, 0, 0))
(13, 'Andrés Molina', 36, 1.85, 'S', datetime.datetime(1988, 3, 3, 0, 0))
(14, 'Patricia León', 38, 1.66, 'S', datetime.datetime(1986, 12, 28, 0, 0))
(15, 'Hugo Paredes', 26, 1.79, 'N', datetime.datetime(1998, 5, 11, 0, 0))
(16, 'Sofía Ortega', 23, 1.58, 'N', datetime.datetime(2001, 10, 5, 0, 0))
(17, 'Manuel Cordero', 41, 1.74, 'S', datetime.datetime(1983, 9, 17, 0, 0))
(18, 'Gabriela Fuentes', 32, 1.67, 'S', datetime.datetime(1992, 6, 9, 0, 0))
(19, 'Ricardo Peña', 21, 1.81, 'N', datetime.datetime(2003, 8, 22, 0, 0))
(20, 'Marta Salas', 34, 1.62, 'S', datetime.datetime(1990, 4, 12, 0, 0))
(21, 'Fernando Ríos', 39, 1.77, 'S', datetime.datetime(1985, 2, 2, 0, 0))
(22, 'Camila Durán', 25, 1.64, 'N', datetime.datetime(1999, 1, 19, 0, 0))
(23, 'Tomás Aguilar', 37, 1.83, 'S', datetime.datetime(1987, 10, 13, 0, 0))
(24, 'Elena Ramos', 20, 1.59, 'N', datetime.datetime(2004, 12, 7, 0, 0))
(25, 'Iván Varela', 27, 1.71, 'N', datetime.datetime(1997, 11, 26, 0, 0))
(26, 'Natalia Jiménez', 31, 1.69, 'S', datetime.datetime(1993, 6, 23, 0, 0))
(27, 'Fabián Cabrera', 29, 1.84, 'N', datetime.datetime(1995, 5, 9, 0, 0))
(28, 'Laura Méndez', 26, 1.63, 'N', datetime.datetime(1998, 9, 30, 0, 0))
(29, 'Samuel Bravo', 42, 1.78, 'S', datetime.datetime(1982, 11, 20, 0, 0))
(30, 'Daniela Vega', 35, 1.6, 'S', datetime.datetime(1989, 2, 27, 0, 0))
(31, 'Esteban Sáenz', 33, 1.82, 'S', datetime.datetime(1991, 1, 11, 0, 0))
(32, 'Julieta Mora', 22, 1.57, 'N', datetime.datetime(2002, 6, 6, 0, 0))
(33, 'Benjamín Torres', 28, 1.76, 'N', datetime.datetime(1996, 7, 3, 0, 0))
(34, 'Ángela Suárez', 36, 1.68, 'S', datetime.datetime(1988, 8, 18, 0, 0))
(35, 'Adrián Lozano', 24, 1.7, 'N', datetime.datetime(2000, 5, 1, 0, 0))
(36, 'Noelia Medina', 30, 1.62, 'S', datetime.datetime(1994, 3, 25, 0, 0))
(37, 'Cristian Lara', 38, 1.79, 'S', datetime.datetime(1986, 4, 14, 0, 0))
(38, 'Silvia Barrios', 27, 1.61, 'N', datetime.datetime(1997, 10, 28, 0, 0))
(39, 'Matías Rojas', 23, 1.73, 'N', datetime.datetime(2001, 12, 12, 0, 0))
(40, 'Rocío Acosta', 32, 1.65, 'S', datetime.datetime(1992, 7, 8, 0, 0))
(41, 'Agustín Castillo', 40, 1.8, 'S', datetime.datetime(1984, 9, 4, 0, 0))
(42, 'Victoria Serrano', 34, 1.67, 'S', datetime.datetime(1990, 8, 2, 0, 0))
(43, 'Javier Salgado', 25, 1.75, 'N', datetime.datetime(1999, 11, 6, 0, 0))
(44, 'Paula Quintero', 28, 1.6, 'N', datetime.datetime(1996, 2, 24, 0, 0))
(45, 'Emilio Estrada', 39, 1.77, 'S', datetime.datetime(1985, 5, 19, 0, 0))
(46, 'Melina Guerra', 21, 1.59, 'N', datetime.datetime(2003, 3, 16, 0, 0))
(47, 'Leandro Vargas', 37, 1.83, 'S', datetime.datetime(1987, 6, 30, 0, 0))
(48, 'Antonia Herrera', 20, 1.62, 'N', datetime.datetime(2004, 1, 2, 0, 0))
(49, 'Sebastián Carrillo', 26, 1.74, 'N', datetime.datetime(1998, 8, 19, 0, 0))
(50, 'Carmen Reyes', 33, 1.68, 'S', datetime.datetime(1991, 9, 25, 0, 0))
╒═════════════╤════════════════════╤════════╤══════════╤══════════╤═════════════════════╕
│   IDPERSONA │ NOMBRE             │   EDAD │   ALTURA │ CASADO   │ FECHA_NAC           │
╞═════════════╪════════════════════╪════════╪══════════╪══════════╪═════════════════════╡
│           1 │ Juan Pérez         │     30 │     1.75 │ S        │ 1994-05-16 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           2 │ María Gómez        │     28 │     1.65 │ N        │ 1996-03-10 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           3 │ Carlos Ruiz        │     35 │     1.8  │ S        │ 1989-07-21 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           4 │ Lucía Fernández    │     22 │     1.6  │ N        │ 2002-01-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           5 │ Pedro Sánchez      │     40 │     1.78 │ S        │ 1984-12-05 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           6 │ Ana Torres         │     27 │     1.68 │ N        │ 1997-08-15 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           7 │ Luis Martínez      │     31 │     1.72 │ S        │ 1993-11-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           8 │ Isabel Díaz        │     45 │     1.63 │ S        │ 1979-06-01 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│           9 │ Diego Romero       │     19 │     1.82 │ N        │ 2005-09-14 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          10 │ Claudia Navarro    │     33 │     1.7  │ S        │ 1991-02-18 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          11 │ José Herrera       │     29 │     1.76 │ N        │ 1995-04-22 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          12 │ Valeria Castro     │     24 │     1.61 │ N        │ 2000-07-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          13 │ Andrés Molina      │     36 │     1.85 │ S        │ 1988-03-03 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          14 │ Patricia León      │     38 │     1.66 │ S        │ 1986-12-28 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          15 │ Hugo Paredes       │     26 │     1.79 │ N        │ 1998-05-11 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          16 │ Sofía Ortega       │     23 │     1.58 │ N        │ 2001-10-05 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          17 │ Manuel Cordero     │     41 │     1.74 │ S        │ 1983-09-17 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          18 │ Gabriela Fuentes   │     32 │     1.67 │ S        │ 1992-06-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          19 │ Ricardo Peña       │     21 │     1.81 │ N        │ 2003-08-22 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          20 │ Marta Salas        │     34 │     1.62 │ S        │ 1990-04-12 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          21 │ Fernando Ríos      │     39 │     1.77 │ S        │ 1985-02-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          22 │ Camila Durán       │     25 │     1.64 │ N        │ 1999-01-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          23 │ Tomás Aguilar      │     37 │     1.83 │ S        │ 1987-10-13 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          24 │ Elena Ramos        │     20 │     1.59 │ N        │ 2004-12-07 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          25 │ Iván Varela        │     27 │     1.71 │ N        │ 1997-11-26 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          26 │ Natalia Jiménez    │     31 │     1.69 │ S        │ 1993-06-23 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          27 │ Fabián Cabrera     │     29 │     1.84 │ N        │ 1995-05-09 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          28 │ Laura Méndez       │     26 │     1.63 │ N        │ 1998-09-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          29 │ Samuel Bravo       │     42 │     1.78 │ S        │ 1982-11-20 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          30 │ Daniela Vega       │     35 │     1.6  │ S        │ 1989-02-27 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          31 │ Esteban Sáenz      │     33 │     1.82 │ S        │ 1991-01-11 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          32 │ Julieta Mora       │     22 │     1.57 │ N        │ 2002-06-06 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          33 │ Benjamín Torres    │     28 │     1.76 │ N        │ 1996-07-03 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          34 │ Ángela Suárez      │     36 │     1.68 │ S        │ 1988-08-18 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          35 │ Adrián Lozano      │     24 │     1.7  │ N        │ 2000-05-01 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          36 │ Noelia Medina      │     30 │     1.62 │ S        │ 1994-03-25 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          37 │ Cristian Lara      │     38 │     1.79 │ S        │ 1986-04-14 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          38 │ Silvia Barrios     │     27 │     1.61 │ N        │ 1997-10-28 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          39 │ Matías Rojas       │     23 │     1.73 │ N        │ 2001-12-12 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          40 │ Rocío Acosta       │     32 │     1.65 │ S        │ 1992-07-08 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          41 │ Agustín Castillo   │     40 │     1.8  │ S        │ 1984-09-04 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          42 │ Victoria Serrano   │     34 │     1.67 │ S        │ 1990-08-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          43 │ Javier Salgado     │     25 │     1.75 │ N        │ 1999-11-06 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          44 │ Paula Quintero     │     28 │     1.6  │ N        │ 1996-02-24 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          45 │ Emilio Estrada     │     39 │     1.77 │ S        │ 1985-05-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          46 │ Melina Guerra      │     21 │     1.59 │ N        │ 2003-03-16 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          47 │ Leandro Vargas     │     37 │     1.83 │ S        │ 1987-06-30 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          48 │ Antonia Herrera    │     20 │     1.62 │ N        │ 2004-01-02 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          49 │ Sebastián Carrillo │     26 │     1.74 │ N        │ 1998-08-19 00:00:00 │
├─────────────┼────────────────────┼────────┼──────────┼──────────┼─────────────────────┤
│          50 │ Carmen Reyes       │     33 │     1.68 │ S        │ 1991-09-25 00:00:00 │
╘═════════════╧════════════════════╧════════╧══════════╧══════════╧═════════════════════╛